### ISSUE TITLE
Investment Report Generation

### ISSUE THREAD

**Issue by izzuddin-noormy** [StamKavid/FinAgent#4]
Hi may I know how do you generate that report for Investment Report Generation, I couldn't find anything similar in your agent code.

**Comment by StamKavid** [comment]
Hello @izzuddin-noormy, try to run the "main" from the agent folder. https://github.com/StamKavid/FinAgent/blob/main/agent/main.py

**Comment by izzuddin-noormy** [comment]
> Hello @izzuddin-noormy, try to run the "main" from the agent folder. https://github.com/StamKavid/FinAgent/blob/main/agent/main.py

Sure mate, let me try it

**Comment by StamKavid** [comment]
Feel free to open a new issue, in case you face any other problem!
